services:
  postgres:
    image: postgres:16-alpine
    container_name: lavadero_db
    restart: always
    environment:
      POSTGRES_DB: lavadero
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: lavadero_backend
    restart: always
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: lavadero
      DB_USER: postgres
      DB_PASSWORD: password
      JWT_SECRET: cambia_esto_por_algo_seguro
      JWT_EXPIRES_IN: 24h
    depends_on:
      - postgres

volumes:
  postgres_data: